version: "3"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/log/postgresql # Add a volume for the logs
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - wownet

  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - ${APPPORT}:${APPPORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - wownet

networks:
  wownet:


volumes:
  pgdata:
  pglogs:
