version: "3.7"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdb/pgdata:/var/lib/postgresql/data
      - ./pgdb/pglogs:/var/log/postgresql # Add a volume for the logs
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - wownet

  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - ${APPPORT}:${APPPORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - wownet

networks:
  wownet:

volumes:
  pgdata:
  pglogs:
